---
apiVersion: v1
kind: Namespace
metadata:
  name: kubestellar
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubestellar
  namespace: kubestellar
---
apiVersion: v1
kind: Service
metadata:
  name: kubestellar-service
  namespace: kubestellar
spec:
  selector:
    app: kubestellar-controller
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestellar
  namespace: kubestellar
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kubestellar-controller
  template:
    metadata:
      labels:
        app: kubestellar-controller
    spec:
      containers:
      - name: kcp-controller
        image: quay.io/kubestellar/kubestellar:v0.3.1
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 6443
          name: kubeapi
          protocol: TCP
      serviceAccountName: kubestellar
