---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubestellar-pvc
  namespace: kubestellar
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestellar-server
  namespace: kubestellar
spec:
  selector:
    matchLabels:
      app: kubestellar-server
  replicas: 1
  template:
    metadata:
      labels:
        app: kubestellar-server
    spec:
      securityContext:
        fsGroup: 1000
        supplementalGroups: [1000]
      volumes:
      - name: kubestellar-pv
        persistentVolumeClaim:
          claimName: kubestellar-pvc
      containers:
      - name: kubestellar-server
        image: quay.io/kubestellar/kubestellar:latest
        imagePullPolicy: Always # IfNotPresent
        securityContext:
           runAsUser: 1000
           runAsGroup: 1000
        volumeMounts:
        - name: kubestellar-pv
          mountPath: "/.kcp"
          readOnly: false
        ports:
        - name: ks-port
          protocol: TCP
          containerPort: 6443
      serviceAccountName: kubestellar
---
kind: Service
apiVersion: v1
metadata:
  name: kubestellar-service
  namespace: kubestellar
spec:
  selector:
    app: kubestellar-server
  ports:
    - protocol: TCP
      port: 6443 # Default port for image
      targetPort: ks-port
---
kind: Service
apiVersion: v1
metadata:
  name: kubestellar-vpc-service
  namespace: kubestellar
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-vpc-lb-name: "kubestellar-lb"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "public"
spec:
  type: LoadBalancer
  selector:
    app: kubestellar-server
  ports:
    - protocol: TCP
      port: 6443 # Default port for image
      targetPort: ks-port
  externalTrafficPolicy: Local 
