---
apiVersion: v1
kind: Namespace
metadata:
  name: kubestellar
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubestellar-service-account
  namespace: kubestellar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubestellar-role
rules:
- resources: [ "secrets" ]
  verbs: [ "create" , "delete" ]
  apiGroups: [ "" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubestellar-role-binding
subjects:
- kind: ServiceAccount
  name: kubestellar-service-account
  apiGroup: ""
  namespace: kubestellar
roleRef:
  kind: ClusterRole
  name: kubestellar-role
  apiGroup: ""
